### ISSUE TITLE
Icon in plugin catalog copied from Feed The Beast

### ISSUE THREAD

**Issue by der-eismann** [tomMoulard/fail2ban#121] opened 2024-05-29 12:08 UTC
Hey everyone, really appreciate the efforts of you and all contributors! However I was a bit surprised to see the fail2ban plugin in the [traefik catalog](https://plugins.traefik.io/plugins/628c9ebcffc0cd18356a979f/fail2-ban) use the (former) logo of popular Minecraft modpack [Feed The Beast](https://feed-the-beast.fandom.com/wiki/Feed_The_Beast). It seems they modernized it a bit, but it's still highly irritating for anyone who knows it and then there's also the copyright aspect. I'm sure this was done without any malicious intent and according to the Authors section in the readme there's quite some creativity available here, so I'd kindly ask you to swap it for something more appropriate :slightly_smiling_face: 
Thanks in advance and keep up the good work!

**Comment by tomMoulard** [comment] 2024-05-29 12:09
Closing as a duplicate of #94

**Closed by tomMoulard** 2024-05-29 12:09 UTC

**Comment by der-eismann** [comment] 2024-05-29 12:14
Why is it still present in the catalog if it was changed 4 months ago? Do you need to change something on the traefik side?

**Comment by tomMoulard** [comment] 2024-05-29 12:16
It is because, there was only one release (https://github.com/tomMoulard/fail2ban/releases/tag/v0.8.0) since, and Traefik failed to import the new version of the plugin (see #120).
There is the package [`slices`](https://github.com/tomMoulard/fail2ban/blob/537c45b8d8033186fa5dd87ece93b623d49a9b5d/pkg/response/status/http_code_range.go#L5) that need not to be used.
